### ISSUE TITLE
doc: Improved semantic

### ISSUE THREAD

**Issue by roiLeo** [materializecss/materialize#102]
Remove `<br>` tags from documentation.
As said by [Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br), 

> Do not use br to create margins between paragraphs; wrap them in p elements and use the CSS margin property to control their size.

Futhermore, there's a accessibility concerns

> Creating separate paragraphs of text using `<br>` is not only bad practice, it is problematic for people who navigate with the aid of screen reading technology. Screen readers may announce the presence of the element, but not any content contained within `<br>`s. This can be a confusing and frustrating experience for the person using the screen reader.
> 
> Use `<p>` elements, and use CSS properties like `margin` to control their spacing.

**Comment by Smankusors** [comment]
hmm interesting. I have a habit of using br tags instead of proper one. I guess it's because easier and faster for me to use br instead haha.

btw, I edited your post, adding more details about accessibility concerns

**Comment by DanielRuf** [comment]
Anyone interested to pick this up? @materializecss/members

**Comment by brennanyoung** [comment]
Yes, assistive tech typically announces `<br>` and `<hr>` because being body markup they are treated as 'real content'. 

You can suppress this by using `<br role="none">` or `<br aria-hidden="true">` but the correct solution for a presentational linebreak or horizontal line is to use CSS.

Only use `<br>` and `<hr>` if the presence of these elements may be regarded as a meaningful part of the content.
