### ISSUE TITLE
Tabs with an identical id and href location get set to display: none

### ISSUE THREAD

**Issue by ChildishGiant** [materializecss/materialize#142]
## Expected Behaviour
The href and id should be able to be the same without the tab being made invisible

## Current Behaviour
If the href and id of a tab are identical (case sensitive), the tab's display is set to none.

## Steps to Reproduce (for bugs)
1. Load https://codepen.io/ChildishGiant/pen/bGqVymm and note that the Apples tab is blanked out
2. Change either the href or id of the apples tab (making one lowercase works)
3. Note that the tab is now visible. 

## Your Environment
* Version used: materialize 1.1.0-alpha
* Browser Name and version:  Chromium: 90.0.4430.93
* Operating System and version: Windows 10 

## Misc
I already filed this on the old repo, would be interested to hear if you guys agree with the comment there: https://github.com/Dogfalo/materialize/issues/6545

**Comment by LoganTann** [comment]
I agree with the comment in the original issue : This is an expected behavior regarding how the component's code works.
I suggest you that tab _button_'s href should point to the tab _section_'s id (and not to the button itself), as intended by the docs' example.

Feel free to reopen this issue if you feel like there is a particular use case/need of your example.
