### ISSUE TITLE
Autocomplete clear button

### ISSUE THREAD

**Issue by Dyskal** [materializecss/materialize#250]
Hi,
Is there a way to have a clear button at the right of the autocomplete component, it would be nice to be able to change the input without deleting each time its content.
Or is there a way in css to do that ?
Thanks.

**Comment by LoganTann** [comment]
Hello,

To display an icon at the right of any `.input-field`, you need to add the class `.suffix` : 
```html
<div class="input-field">
  <i class="material-icons suffix">clear</i>
  <input type="text" id="autocomplete-input" class="autocomplete" value="click on the cross to clear the field">
  <label for="autocomplete-input">Autocomplete</label>
</div>
```

Then, to clear the input using this icon, we just need to register a click event.
Since selecting the `<input>` element is required to initialize the autocomplete component, selecting our icon from the parent element is simple : 
```js
var elems = document.querySelectorAll('.autocomplete');
var instances = M.Autocomplete.init(elems, {/* ... */});

// 👇
for (const field of elems) {
  const clearIcon = field.parentElement.querySelector(".suffix");
  if (!clearIcon) continue;
  clearIcon.addEventListener("click", function() {
    field.value="";
  });
}
```

If browser compatibility does not matter (ff 74+ & chrome 80+), you can simplify the code using a nullsafe operator and an arrow function, and even use the classic `elem.onclick = ...` instead of registering a query selector.  
Notice that only one `<input>` and one `<i class="suffix">` tags should be inside the `<div class="input-field">` tag.


I created a codepen demo implementing this fix here : https://codepen.io/shinprog/pen/WNXavXZ


Issue closed since it's pretty simple to implement.
Feel free to reopen if you think it have to be added to the lib.

**Comment by Dyskal** [comment]
Thanks a lot for your quick answer.
I have one more question, I already had a prefix for my input and when I add the suffix, it goes above the input, is there a way to fix that ?

**Comment by LoganTann** [comment]
> Thanks a lot for your quick answer. I have one more question, I already had a prefix for my input and when I add the suffix, it goes above the input, is there a way to fix that ?
Hmm strange, I don't have this problem if I add a prefix icon.

![image](https://user-images.githubusercontent.com/28659185/155896910-6cc518d9-a84e-4483-8b69-5e486cf76eda.png)

Could you share your code ?

**Comment by Dyskal** [comment]
I had a problem with my code sorry, everything works fine now !
