### ISSUE TITLE
Laggyness on sidenav for WebKit

### ISSUE THREAD

**Issue by Herna1994** [materializecss/materialize#264]
Using sidenav on webkit becomes laggy.

I have noticed that everytime I open and close the sidenav, the style gets applied with transform: translateX(-105%) and with transform: translateX(0%) but doesn't apply the -webkit part of it to its style.

With this, using the sidenav on iPhones makes the experience way laggy, with both Safari and Chrome browsers.

**Comment by wuda-io** [comment]
Which version are you using?
As far as I researched webkittransform is deprecated.
Also check out this: [https://developer.mozilla.org/en-US/docs/Web/CSS/transform](https://developer.mozilla.org/en-US/docs/Web/CSS/transform)
Should work in Safari since version 9.
Also can be that the animejs lib caused the flickering... In the next release there should be no animejs anymore. So CSS only.
Please provide more details and reopen this issue if it still occurs. Thanks.
