### ISSUE TITLE
Ripple breaks if you click it fast enough

### ISSUE THREAD

**Issue by Duplore** [materializecss/materialize#293]
![image](https://user-images.githubusercontent.com/40915035/196526809-de5dcc82-d824-47e1-ba21-ea07c5a78880.png)
![image](https://user-images.githubusercontent.com/40915035/196526939-8262cbc4-383d-4186-a0cc-1d8a9cf429fe.png)

**Comment by Duplore** [comment]
it will remain like this till you refresh the page to fix it, but you can just break it again by repeating it

**Comment by DanielRuf** [comment]
Hi @Duplore,

Thanks for reporting this. What version of materializecss do you use?

We use a customized version of waves.js and this is well-known problem in there.

https://github.com/materializecss/materialize/blob/main/js/waves.js
https://github.com/fians/Waves

https://github.com/fians/Waves/issues/179 is just one of the known public bugreports regarding this exact error.

@wuda-io we might have to check our version or add the prposed patch.

Because at https://github.com/materializecss/materialize/commits/main/js/waves.js I see some changes that could already have added the right patches.

**Comment by Duplore** [comment]
@DanielRuf i am using 1.1.0

**Comment by Duplore** [comment]
@wuda-io easy to break it get like a few buttons or what ever and spam all of them and at random it will turn grey and will remain like that till you refresh the page lol

**Comment by wuda-io** [comment]
Ok strange, I use Firefox and Windows most of the time, and it never breaks here.. what OS and which browser are you using?

**Comment by Duplore** [comment]
@wuda-io  brave browser

**Comment by wuda-io** [comment]
new implementation in [v2-dev](https://github.com/materializecss/materialize/tree/v2-dev)
