### ISSUE TITLE
Suggestion: A Disclaimer that the lib uses anime.js internally

### ISSUE THREAD

**Issue by Mashiane** [materializecss/materialize#425]
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

I just opened the js file using visual studio and noticed that it includes anime.js. I love and use anime.js and I guess I would have included it in my app if I didnt check this out.

This is not an issue though, if you dont mind me asking, the included anime.js is the *full* or an adopted chopped and changed version to suit your needs?

### Current Behavior

See Context

### Expected behavior

See Context

### Possible Solutions or Causes

See Context

### Your Environment

* Version used: Checking out the alpha
* Browser Name and version: Brave 
* Operating System and version (desktop or mobile): Windows 10
* Additional information you want to tell us:

**Comment by wuda-io** [comment]
Hello @Mashiane!
Thanks for pointing it out. I think in the nearer future we should remove the dependency completely,
because it is only using 4 functions or so, which could be done with CSS Animations i guess.

It would be awesome if someone has time to fix this stuff and we do not have to rely on this library.
AnimeJs is great and I use it for other projects too, but in the sense of a fast Web-UI I think it is overpowered.

Also: As far as I know, CSS Animations use the GPU for rendering and Animejs would use Computation-Power  via CPU.
So I would prefer the more performant GPU-Path.

**Comment by wuda-io** [comment]
In the latest release *2.0.3* animejs is not used anymore.
