### ISSUE TITLE
[Bug]:  background color of the body is not set with the last release (2.0.3-alpha)

### ISSUE THREAD

**Issue by OlivierMadant** [materializecss/materialize#427]
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

Hello,

There seems to be a problem with the latest version (2.0.3-alpha). The dist/materialize.min.css does not give the same result as https://materializeweb.com/css/ghpages-materialize.css used in the documentation website.

With the following codepen, if I use the released materialize.min.css then the background color of the body is not set: https://codepen.io/Olivier-Madant/pen/xxmJbGq
If I use the same code with the css file used by the website, it looks good : https://codepen.io/Olivier-Madant/details/MWZBYya

With the version using the released materialize.min.css, if we add 

body {
    background-color: var(--background-color);
}

This fixes the problem.

Is it normal for the documentation website uses another version of the css? Do we have an issue with  background-color on the release version?

By the way, Thank you for this new version and your excellent work,

Olivier

### Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Additional information you want to tell us:

**Comment by danice** [comment]
This is by design and it was the same in previous releases.

It you check, this body property is set in `style.scss` and this file is only included in `ghpages-materialize.scss`, but not in `materialize.scss`. (in fact `ghpages-materialize.scss` is just `materialize.scss` plus `style.scss`).

Is a good think to differentiate from styles needed for the components and those to be used in the website. 
This separation will be more clear if we split the website project from the components project.

If you need the same styles from the website, you can just add a copy this styles files like in ghpages-materialize.scss.
