### ISSUE TITLE
Provide a new CDN Version Link

### ISSUE THREAD

**Issue by wuda-io** [materializecss/materialize#6]
Hello!

I have been using this Library since many years now and I like it a lot. Thank you for continuing the Project. Ive been following from the start here. Maybe I can contribute something too.

I compiled the latest version myself, but it would be cool to have a CDN Link for a quick usage and testing. I think we should use free CDNs for the start. So this Project would get more interaction also from newcomers.

Thanks for pushing materializecss forward <3

**Comment by DanielRuf** [comment]
> I compiled the latest version myself, but it would be cool to have a CDN Link for a quick usage and testing

Most CDNs like unpkg and jsdelivr already use the npm ecosystem, and also cdnjs. So no need to do something there as they automatically fetch the releases when we publish them.

Projects should ideally not use CDNs because they can be offline in the (far) future, have outages and be problematic regarding GDPR.

Nonetheless we will keep using the same CDN like the original project does (cdnjs) or provide more: https://materializecss.com/getting-started.html

As there is nothing to do here (besides changing the name in the cdnjs link in the future) we can close this issue as resolved.

> Maybe I can contribute something too.

You are very welcome to provide PRs.

**Comment by DanielRuf** [comment]
>  I think we should use free CDNs for the start

I am not aware of paid CDNs for opensource projects ;-)
