### ISSUE TITLE
Feature Request: materialize css email templates

### ISSUE THREAD

**Issue by nh916** [materializecss/materialize#82]
I think this is one of those things that will take materialize to the next level. I saw this on zurb foundation css and it just blew me out the water. 

They give the developers free and good email templates for most common needs such as "forgot password", "marketing",  "welcome", and "newsletter" This is the coolest thing to me and I thought if in the future we can implement something similar for materialize css that would be amazing too!

This is not essential, but just something I thought would give us a huge boost in awesomeness!

here is a link to how zurb foundation is currently doing it
https://get.foundation/emails/email-templates.html

**Comment by DanielRuf** [comment]
Ex-Foundation maintainer / core contributor here.

In general CSS for emails is quite compliated and you need some tricks like `Margin` (yes, a big `M`). Also see https://www.caniemail.com/. To support and test a wide range of clients (https://testi.at/ might be helpful for tests) you have to consider many things and special edge cases in CSS and HTML.

I fear this could become an extra project like foundation-emails with its own bugtracker, issues, team and so on. Because the markup is not enough, you also need the right styles, some tools for users (like an inliner), tests (browserstack would not work here, but maybe testi.at) and so on.

**Comment by wuda-io** [comment]
I also think this is out of scope of this project.
